# Use the official PostgreSQL image
FROM postgres:alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=post123
ENV POSTGRES_DB=mydatabase

# Expose PostgreSQL port
EXPOSE 5432